/* nienumeryczne numery wersji lub wariantów */
SELECT PART_NO,REVISION,REVISION_NAME,ALTERNATIVE,ALTERNATIVE_DESCRIPTION
from dbo.ifs_struktury as ifs
WHERE 1 = 1
AND ifs.ALTERNATIVE != '*'
AND ifs.REVISION != '*'
AND
(
ISNUMERIC(ifs.ALTERNATIVE )=0
OR ISNUMERIC(ifs.REVISION)=0
)
GROUP BY PART_NO,REVISION,REVISION_NAME,ALTERNATIVE,ALTERNATIVE_DESCRIPTION
ORDER BY PART_NO,REVISION,REVISION_NAME,ALTERNATIVE,ALTERNATIVE_DESCRIPTION