/* GENEROWANIE PLIKU CSV DO PORÓWNANIA MARSZRUT */

SELECT CONTRACT
 , PART_NO
 , ALTERNATIVE_NO
 , ROUTING_REVISION
--
 , OPERATION_NO
 , OPERATION_DESCRIPTION
--
 , WORK_CENTER_NO
 , trim(to_char( MACH_RUN_FACTOR,'999990.99999')) MACH_RUN_FACTOR
--
 , LABOR_CLASS_NO 
 , trim(to_char(LABOR_RUN_FACTOR,'999990.99999')) as LABOR_RUN_FACTOR
 , trim(to_char(CREW_SIZE,'999990.99999')) as CREW_SIZE
 --
 , RUN_TIME_CODE
 --
 , SETUP_LABOR_CLASS_NO
 , trim(to_char(MACH_SETUP_TIME,'999990.99999')) as MACH_SETUP_TIME
 , trim(to_char(LABOR_SETUP_TIME,'999990.99999')) as LABOR_SETUP_TIME
 , trim(to_char(SETUP_CREW_SIZE,'999990.99999')) as SETUP_CREW_SIZE 
 --
 , trim(to_char(MOVE_TIME,'999990.99999')) as MOVE_TIME
 , trim(to_char(OVERLAP,'999990.99999')) as OVERLAP
--
--  , EFFICIENCY_FACTOR
--  , LOT_QTY
--  , PHASE_IN_DATE
--  , PHASE_OUT_DATE
--
FROM ROUTING_OPERATION r
WHERE 1 = 1 
and INVENTORY_PART_API.Get_Part_Status(r.CONTRACT,r.PART_NO) = 'A'
and  r.PHASE_OUT_DATE is null
-- AND CONTRACT = 'KT1' 
-- AND ( PART_NO LIKE 'MIE.%'  OR PART_NO LIKE 'NAW.%' )

