use mwtech;

DECLARE @PART_NO as VARCHAR(30) 
DECLARE @REVISION as VARCHAR(30) 
DECLARE @ALTERNATIVE as VARCHAR(30) 

SET @PART_NO = 'MIE.DS55-1'
SET @REVISION = '2'
SET @ALTERNATIVE = '1'

select REVISION,ALTERNATIVE,LINE_SEQUENCE,PART_NO,COMPONENT_PART,PARTS_BY_WEIGHT,SHRINKAGE_FACTOR   
from dbo.ifs_receptury
WHERE 1 = 1 
AND PART_NO = @PART_NO
AND REVISION = @REVISION
-- AND ALTERNATIVE = @ALTERNATIVE
ORDER by REVISION,ALTERNATIVE,LINE_SEQUENCE

select REVISION,ALTERNATIVE,LINE_SEQUENCE,PART_NO,COMPONENT_PART,QTY_PER_ASSEMBLY,SHRINKAGE_FACTOR  
from dbo.mwtech_bom_ifs
WHERE 1 = 1 
AND PART_NO = @PART_NO
AND REVISION = @REVISION
-- AND ALTERNATIVE = @ALTERNATIVE
ORDER by REVISION,ALTERNATIVE,LINE_SEQUENCE
